version: '3.5'
services:

  postgres:
    container_name: postgres-wefox
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-wefox}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
